apiVersion: apps/v1
kind: Deployment
metadata:
  name: blacklist-service
  labels:
    app: blacklist-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blacklist-service
  template:
    metadata:
      labels:
        app: blacklist-service
    spec:
      containers:
        - name: blacklist-service
          image: samaelarch/unipool_blacklist_service:latest
          imagePullPolicy: Always
          # resources:
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
          ports:
            - containerPort: 8083
          volumeMounts:
            - name: log-path
              mountPath: /var/log/unipool
      volumes:
        - name: log-path
          hostPath:
            path: /var/log/unipool
          env:
            - name: DATABASE_URL
              value: jdbc:postgresql://postgres-db:5432/uniPooldb
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: unipool-secret
                  key: DATABASE_USERNAME
            - name: DATABASE_PASS
              valueFrom:
                secretKeyRef:
                  name: unipool-secret
                  key: DATABASE_PASS
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
---
apiVersion: v1
kind: Service
metadata:
  name: blacklist-service-svc
spec:
  selector:
    app: blacklist-service
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8083
