apiVersion: apps/v1
kind: Deployment
metadata:
  name: blacklist-service
  labels:
    app: blacklist-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blacklist-service
  template:
    metadata:
      labels:
        app: blacklist-service
    spec:
      containers:
        - name: blacklist-service
          image: samaelarch/unipool_blacklist_service:latest
          imagePullPolicy: Always
          # resources:
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
          ports:
            - containerPort: 8083

---
apiVersion: v1
kind: Service
metadata:
  name: blacklist-service-svc
spec:
  selector:
    app: blacklist-service
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8083
