- name: Deploy configurations and DB
  hosts: all
  pre_tasks:
    - name: Check Minikube's status.
      command: minikube status
      register: minikube_status
      changed_when: false
      ignore_errors: true
    # Otherwise will start minikube
    - name: Start Minikube if it's not running.
      command: minikube start --vm-driver=docker --cpus 4 --memory 9152
      when: "not minikube_status.stdout or 'Running' not in minikube_status.stdout"
    - name: "Install kubernetes python package"
      pip:
        name: kubernetes
        state: present
  tasks:
    - name: Delete any existing Secrets config
      kubernetes.core.k8s:
        src: secrets.yml
        state: absent
        namespace: default
    - name: Delete any existing deployment of Postgres deployment
      kubernetes.core.k8s:
        src: postgres-deployment.yml
        state: absent
        namespace: default
    - name: Delete any existing deployment of Postgres storage
      kubernetes.core.k8s:
        src: postgres-storage.yml
        state: absent
        namespace: default
    - name: Configure secrets
      kubernetes.core.k8s:
        src: secrets.yml
        state: present
        namespace: default
    - name: Create a deployment of Postgres deployment
      kubernetes.core.k8s:
        src: postgres-deployment.yml
        state: present
        namespace: default
    - name: Create a deployment of Postgres storage
      kubernetes.core.k8s:
        src: postgres-storage.yml
        state: present
        namespace: default
